/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DirectoryService } from "../directory.service";
import { DirectoryCreateInput } from "./DirectoryCreateInput";
import { Directory } from "./Directory";
import { DirectoryFindManyArgs } from "./DirectoryFindManyArgs";
import { DirectoryWhereUniqueInput } from "./DirectoryWhereUniqueInput";
import { DirectoryUpdateInput } from "./DirectoryUpdateInput";
import { ListingFindManyArgs } from "../../listing/base/ListingFindManyArgs";
import { Listing } from "../../listing/base/Listing";
import { ListingWhereUniqueInput } from "../../listing/base/ListingWhereUniqueInput";

export class DirectoryControllerBase {
  constructor(protected readonly service: DirectoryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Directory })
  async createDirectory(
    @common.Body() data: DirectoryCreateInput
  ): Promise<Directory> {
    return await this.service.createDirectory({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Directory] })
  @ApiNestedQuery(DirectoryFindManyArgs)
  async directories(@common.Req() request: Request): Promise<Directory[]> {
    const args = plainToClass(DirectoryFindManyArgs, request.query);
    return this.service.directories({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Directory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async directory(
    @common.Param() params: DirectoryWhereUniqueInput
  ): Promise<Directory | null> {
    const result = await this.service.directory({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Directory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDirectory(
    @common.Param() params: DirectoryWhereUniqueInput,
    @common.Body() data: DirectoryUpdateInput
  ): Promise<Directory | null> {
    try {
      return await this.service.updateDirectory({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Directory })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDirectory(
    @common.Param() params: DirectoryWhereUniqueInput
  ): Promise<Directory | null> {
    try {
      return await this.service.deleteDirectory({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/listings")
  @ApiNestedQuery(ListingFindManyArgs)
  async findListings(
    @common.Req() request: Request,
    @common.Param() params: DirectoryWhereUniqueInput
  ): Promise<Listing[]> {
    const query = plainToClass(ListingFindManyArgs, request.query);
    const results = await this.service.findListings(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        description: true,
        contactInfo: true,
        title: true,
        address: true,

        directory: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/listings")
  async connectListings(
    @common.Param() params: DirectoryWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listings: {
        connect: body,
      },
    };
    await this.service.updateDirectory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/listings")
  async updateListings(
    @common.Param() params: DirectoryWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listings: {
        set: body,
      },
    };
    await this.service.updateDirectory({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/listings")
  async disconnectListings(
    @common.Param() params: DirectoryWhereUniqueInput,
    @common.Body() body: ListingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listings: {
        disconnect: body,
      },
    };
    await this.service.updateDirectory({
      where: params,
      data,
      select: { id: true },
    });
  }
}
